language: bash
services: docker

env:
  global:
    - IMAGE=drpsychick/docker-linuxgsm-ubuntu
  matrix:
    - UBUNTU_VERSION=latest
    - UBUNTU_VERSION=focal
    - UBUNTU_VERSION=eoan
    - UBUNTU_VERSION=disco
    - UBUNTU_VERSION=bionic
    - UBUNTU_VERSION=xenial

before_script:
  - docker build -t test --build-arg UBUNTU_VERSION=$UBUNTU_VERSION .
  - VERSION=$(eval $(docker run --rm test grep ^version= linuxgsm.sh); echo $version)
  - eval $(ssh-agent -s)
  - echo "$DEPLOY_PRIVATE_KEY" | ssh-add - && ssh-add -l
  - git config --global user.email "github@drsick.net"
  - git config --global user.name "TAG bot"
  - git remote set-url origin "git@github.com:DrPsychick/docker-linuxgsm-ubuntu.git"


script:
  # test always passes
  - echo "Ubuntu $UBUNTU_VERSION linuxgsm $VERSION"
  - >
    echo "Running tests...";
    docker run test linuxgsm.sh list

after_success:
  - >
    if [ "$TRAVIS_BRANCH" = "develop" -a "$UBUNTU_VERSION" = "latest" ]; then
    curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "develop"}'
    -X POST "$DOCKERHUB_TRIGGER";
    fi
  - >
    if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    if [ "$UBUNTU_VERSION" = "latest" ]; then
    curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "master"}'
    -X POST "$DOCKERHUB_TRIGGER";
    else
    branch="${VERSION}-${UBUNTU_VERSION}";
    echo "Branch: $branch";
    git checkout -b $branch;
    git pull -X theirs --no-edit --no-commit origin $branch;
    git merge -X theirs --no-edit --no-commit master;
    sed -i -e "s/UBUNTU_VERSION=.*/UBUNTU_VERSION=$UBUNTU_VERSION/" Dockerfile;
    git diff Dockerfile;
    docker build -t $IMAGE:$branch --build-arg UBUNTU_VERSION=$UBUNTU_VERSION . || exit 1;
    git commit -a -m "automated build on $branch";
    git push -u origin $branch;
    fi;
    fi
